# Generated by Django 2.2.5 on 2019-11-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191108_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='defualt.jpg', upload_to='profile_pics'),
        ),
    ]
