# Generated by Django 2.2.5 on 2019-12-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191206_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalcliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
