# Generated by Django 2.2.5 on 2019-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sucursalcliente_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='imagenTkn',
            field=models.ImageField(default='token_pics/default.jpg', upload_to='token_pics'),
        ),
    ]
