# Generated by Django 2.2.5 on 2019-12-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191207_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='imagenTkn',
            field=models.ImageField(default='token_pics/default.png', upload_to='token_pics'),
        ),
    ]
